dist: xenial

language: go

go:
  - 1.13.x

git:
  depth: 1

before_script:
  - sudo apt-get update
  - sudo apt-get install curl -y
  - chmod +x ./scripts/verify-protoc-gen.sh
  - go get -v -u golang.org/x/lint/golint

script:
  - make dep
  - make lint
  - make verify-protoc-gen
  - make test
